apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: chinchilla-python 
  janus-idp.io/tekton: chinchilla-python
  backstage.io/kubernetes-id: chinchilla-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: chinchilla-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  